name: Carga Histórico
on:
  workflow_dispatch:
jobs:
  single_run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ejecutar ex_gnoticias_historico.py
        run: |
          echo "Ejecutando la tarea a las $(date)"
          PYTHONPATH=. python gnoticias/ex_gnoticias_historico.py
      - name: Commit and push database changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/gnoticias.db
          if ! git diff --staged --quiet; then
            git commit -m "chore(data): Update database with new news (histórico)"
            git pull --rebase
            git push
          else
            echo "No changes to the database to commit."
          fi
